[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
somnia_testnet = "https://dream-rpc.somnia.network"
somnia_mainnet = "https://rpc.somnia.network"
# Alternative endpoints
somnia_testnet_thirdweb = "https://50312.rpc.thirdweb.com"
somnia_testnet_ankr = "https://rpc.ankr.com/somnia_testnet"

[etherscan]
somnia_testnet = { key = "your_key_here", url = "https://explorer-testnet.somnia.network/api" }
